# Generated by Django 4.0.10 on 2023-07-02 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentfurlax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='furnitureoptionid',
        ),
        migrations.AddField(
            model_name='furniture',
            name='color',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='imageurl',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='size',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='rentalOptions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lineitem', to='rentfurlax.rentaloptions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FurnitureOptions',
        ),
    ]
